
-- SCHEMA SH --> SALES HISTORIY (SH)


-- ESTAS DOS COLUMNAS SIRVEN O FUNCIONAN DE CIERTA MANERA PARA ADEMINISTRAR 
-- LOS DATOS YA QUE NOS AYUDAN HA HACER ESTO Y MÁS ROWID QUE DE CIERTA MANERA 
-- FUNCIONA COMO INDICANDO LA REFERENCIA DE MEMORIA DE UNA FILA EN CONCRETO 
-- DE UNA TABLA 
SELECT rownum, rowid, prod_id, prod_name prod_category, prod_status FROM sh.PRODUCTS;

-- PODEMOS HACER USO PARA APLICAR FILTROS EN OTRAS COSAS 
-- TAMBIEN NOS PERMITE ELIMINAR ELEMENTOS ENTRE OTRAS COSAS DE MODIFICACIÓN 
-- AUNQUE REALMENTE COMO LO MENCIONO ANTERIORMENTE 
-- ESTO FUNCIONA MÁS PARA ADMINISTRACIÓN DE BASES DE DATOS 
SELECT rownum, rowid, prod_id, prod_name prod_category, prod_status FROM sh.PRODUCTS
    WHERE rowid IN('AABZJIAAEAABmirAAA', 'AABZJIAAEAABmirAAC');

-- TAMBIEN PODEMOS HACER OPERACIONES CON ROWNUM PERO SERIAN MÁS DE CONSULTA
SELECT rownum, rowid, prod_id, prod_name prod_category, prod_status FROM sh.PRODUCTS
    WHERE rownum < 10; 
