-- SCHEMA SH 

-- DEFINE Y UNDEFINE 

-- ESTAS DOS SENTENCIAS NOS SIRVEN PARA PODER ESTABLECER 
-- VALORES A VARIABLES O DE CIERTA FORMA CREAR VARIABLES YA INICIALIZADAS 

SELECT * FROM sh.products; 

-- DEFINIR VARIABLES 

DEFINE min_price = 800; 
DEFINE max_price = 900; 

-- VISUALIZAR LAS VARIABLES QUE HAN SIDO CREADAS
DEFINE; 

-- PARA UTILIZARLAS EN CONSULTAS ENTRE OTRAS OPERACIONES SE DEBE 
-- DE PONER EL & SIN OLVIDAR QUE SI ALMACENAN CARACTERES SE DEBE 
-- DE UTILIZAR LAS COMILLAS SIMPLES ''

SELECT * FROM sh.products 
    WHERE prod_min_price BETWEEN &min_price AND &max_price; 

-- PARA DESASIGNARLE UN VALOR A UNA DE LAS VARIABLES SE HACE CON 
-- UNDEFINE 

UNDEFINE min_price; 
UNDEFINE max_price; 
