-- SCHEMA SH 

-- OPERACIONES CON CARACTERES 

-- UPPER --> CONVIERTE TODOS LOS CARACTERES EN MAYUSCULA 
SELECT UPPER(prod_name) FROM sh.products; 

-- LOWER --> CONVIERTE TODOS LOS CARACTERES EN MINUSCULA
SELECT LOWER(prod_name) FROM sh.products; 

-- INITCAP --> PRIMER CARACTER EN MAYUSCULA 
SELECT INITCAP(prod_name) FROM sh.products; 

-- SUBSTR --> ESTRAER CARACTERES DE UNA POSICIÓN Y UNA CANTIDAD 
SELECT SUBSTR(prod_name, 5, 10) FROM sh.products; 
SELECT SUBSTR(prod_name, 10) FROM sh.products; 

-- LENGTH --> CONTAR LA CANTIDAD DE CARACTERES DE UNA CADENA 
SELECT LENGTH(prod_name) FROM sh.products; 