-- SCHEMA SH 

-- HAVING - CONDICIONES PARA LOS GRUPOS OSEA UN WHERE PARA LOS GROUP BY 

-- GROUP BY POR SUMAS - COSTOS Y GANANCIAS
SELECT prod_id, SUM(unit_cost) AS SUMA_TOTAL_DE_COSTOS, 
SUM(unit_price) AS SUMA_TOTAL_VENTAS FROM sh.costs 
    GROUP BY prod_id HAVING SUM(unit_cost) >= 10000  
    ORDER BY SUM(unit_price); 

-- EL USO DE HAVING SE ESTABLE DESPUES DE HACER GROUP BY PARA QUE LOGRE FUNCIONAR CORRECTAMENTE 

SELECT DISTINCT promo_category FROM sh.promotions; 

SELECT * FROM sh.promotions; 

-- COSTO TOTAL DE TODAS LAS PROMOCIONES CREADAS 
SELECT promo_category, SUM(promo_cost) AS COSTO_DE_PROMOCION_CATEGORIA
    FROM sh.promotions GROUP BY promo_category HAVING SUM(promo_cost) > 100000
    ORDER BY SUM(promo_cost); 

